In [37]:
import pandas as pd
import sqlite3

conn = sqlite3.connect('netflix.sqlite')
cursor = conn.cursor()

Создал таблицу Actors

In [38]:
cursor.execute('''CREATE TABLE Actors (
                    id INTEGER PRIMARY KEY,
                    actor_name TEXT
                )''')

Перенос id и cast

In [39]:
cursor.execute('''INSERT INTO Actors (id, actor_name)
                  SELECT show_id, [cast]
                  FROM netflix_titles''')

In [40]:
pd.read_sql("SELECT * FROM Actors", conn)

            id                                         actor_name
0       247747  Vinod Khanna, Rishi Kapoor, Amitabh Bachchan, ...
1       269880  Will Smith, Martin Lawrence, Téa Leoni, Tchéky...
2       281550  Lou Diamond Phillips, Esai Morales, Rosanna De...
3       284890  Twinkle Khanna, Bobby Deol, Danny Denzongpa, R...
4       292118  Mike Judge, Bruce Willis, Demi Moore, Cloris L...
...        ...                                                ...
6229  81224868  Bill Rogers, Carrie Savage, Ken Spassione, Ang...
6230  81227195  Thabo Rametsi, Thabo Malema, Welile Nzuza, Jaf...
6231  81228864  Joey Rasdien, David Kau, David Kibuuka, Chris ...
6232  81235603  Tara Strong, Kevin Thoms, Brian Posehn, John D...
6233  81235729  Tiffany Tenille, Numa Perrier, Stephen Barring...

[6234 rows x 2 columns]

Создание таблицы актеры-фильм

In [41]:
cursor.execute('''CREATE TABLE actor_films (
                    id INTEGER,
                    actors TEXT,
                    film_title TEXT,
                    FOREIGN KEY (id) REFERENCES Actors(id)
                )''')

Заполнение таблицы

In [42]:
cursor.execute('''INSERT INTO actor_films (id, actors, film_title)
                  SELECT nt.show_id, ac.actor_name, nt.title
                  FROM netflix_titles nt
                  INNER JOIN Actors ac ON nt.show_id = ac.id''')

In [43]:
pd.read_sql("SELECT * FROM actor_films", conn)

,id,actors,film_title
0,81145628,"Alan Marriott, Andrew Toth, Brian Dobson, Cole...",Norm of the North: King Sized Adventure
1,80117401,Jandino Asporaat,Jandino: Whatever it Takes
2,70234439,"Peter Cullen, Sumalee Montano, Frank Welker, J...",Transformers Prime
3,80058654,"Will Friedle, Darren Criss, Constance Zimmer, ...",Transformers: Robots in Disguise
4,80125979,"Nesta Cooper, Kate Walsh, John Michael Higgins...",#realityhigh
...,...,...,...
6229,80000063,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",Red vs. Blue
6230,70286564,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",Maron
6231,80116008,,Little Baby Bum: Nursery Rhyme Friends
6232,70281022,"Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...",A Young Doctor's Notebook and Other Stories
6233,70153404,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",Friends

In [44]:
conn.commit()
conn.close()